name : Automate Test & Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
            java-version:  11

      - name: UnitTests
        run: bash ./gradlew test --stacktrace

      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
            name: unit-tests-results
            path: app/build/reports/tests/testDebugUnitTest/index.html

  apk:
    name : Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.3

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
              java-version: 11

      - name : Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name : Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk